# -*- mode: ruby -*-
# vi: set ft=ruby :

branch = `git rev-parse --abbrev-ref HEA'xdebug.'xdebug.`

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  # hostname.
  # need to fix Could not retrieve fact fqdn
  config.vm.hostname = "fanntictactoe.dev"

  # See https://docs.vagrantup.com/v2/getting-started/networking.html
  config.vm.provision :shell, path: "bootstrap.sh"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "10.10.10.33"

  # Using vagrant-bindfs. See https://github.com/gael-ian/vagrant-bindfs
  #
  # Declare shared folder with Vagrant syntax
  config.vm.synced_folder "../../", "/mnt/vagrant-nfs", type: :nfs

  # Use vagrant-bindfs to re-mount folder
  config.bindfs.bind_folder "/mnt/vagrant-nfs", "/home/vagrant/corretgecom"


  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|

  #   # Don't boot with headless mode
  #   vb.gui = true
  #
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.name = "corretgecom"
    vb.cpus = 2
    vb.memory = 512
    # See http://askubuntu.com/questions/238040/how-do-i-fix-name-service-for-vagrant-client
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.
  #
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "develop.pp"
    puppet.options = ['--verbose']
  end

end
